catalogs:
  dev:
    '@eslint/config-inspector': ^1.1.0
    '@types/node': ^24.1.0
    '@types/react': ^19.1.8
    eslint-typegen: ^2.2.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  peer:
    eslint: ^9.31.0
  peer.react:
    '@eslint-react/eslint-plugin': ^1.52.3
    eslint-plugin-react-google-translate: ^0.1.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
  prod:
    '@antfu/eslint-config': ^4.17.0
    eslint-plugin-format: ^1.0.1
    local-pkg: ^1.1.1
